package project

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"time"
)

// ScaffoldOptions options for generating a new Ikemen GO project
type ScaffoldOptions struct {
	Name          string
	TargetDir     string
	EngineVersion string
	EngineChannel string
	EnginePath    string // Optional path to cached engine files to copy base assets from
	Author        string
}

// DefaultSelectDefContent standard initial select.def
const DefaultSelectDefContent = `;-------------------------------------------------------------------
; Ikemen GO - select.def
; Generated by Ikemen GO Studio
;-------------------------------------------------------------------

[Characters]
; Insert character folder names or .def paths below
; e.g.: kfm, stages/my_stage.def

[ExtraStages]
; Insert extra stage paths below
; e.g.: stages/stage0.def

[Options]
arcade.maxmatches = 6,1,1,0,0,0,0,0,0,0
team.maxmatches = 4,1,1,0,0,0,0,0,0,0
`

// Scaffold creates a new project directory structure and base files
func Scaffold(opts ScaffoldOptions) (*ProjectManifest, error) {
	if opts.TargetDir == "" {
		return nil, fmt.Errorf("target directory cannot be empty")
	}
	if opts.Name == "" {
		return nil, fmt.Errorf("project name cannot be empty")
	}
	if opts.EngineVersion == "" {
		opts.EngineVersion = "latest"
	}
	if opts.EngineChannel == "" {
		opts.EngineChannel = "stable"
	}

	// 1. Create root directory
	if err := os.MkdirAll(opts.TargetDir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create project directory: %w", err)
	}

	// 2. Create standard folder structure
	standardDirs := []string{
		"chars",
		"stages",
		"data",
		"font",
		"sound",
		"external",
	}

	for _, dir := range standardDirs {
		dirPath := filepath.Join(opts.TargetDir, dir)
		if err := os.MkdirAll(dirPath, 0755); err != nil {
			return nil, fmt.Errorf("failed to create directory %s: %w", dir, err)
		}
	}

	// 3. If engine path is provided, copy default base system assets (external, lib, data, font, sound, stages, video)
	if opts.EnginePath != "" {
		if fi, err := os.Stat(opts.EnginePath); err == nil && fi.IsDir() {
			_ = EnsureProjectRuntimeAssets(opts.EnginePath, opts.TargetDir)
		}
	}

	// 4. Ensure select.def exists in data/
	selectDefPath := filepath.Join(opts.TargetDir, "data", "select.def")
	if _, err := os.Stat(selectDefPath); os.IsNotExist(err) {
		if err := os.WriteFile(selectDefPath, []byte(DefaultSelectDefContent), 0644); err != nil {
			return nil, fmt.Errorf("failed to create select.def: %w", err)
		}
	}

	// 5. Create project manifest
	manifest := &ProjectManifest{
		Name:    opts.Name,
		Version: "0.1.0",
		Engine: EngineConfig{
			Version: opts.EngineVersion,
			Channel: opts.EngineChannel,
		},
		CreatedAt: time.Now().UTC(),
		UpdatedAt: time.Now().UTC(),
		Author:    opts.Author,
		Path:      opts.TargetDir,
	}

	if err := SaveManifest(opts.TargetDir, manifest); err != nil {
		return nil, fmt.Errorf("failed to save manifest: %w", err)
	}

	return manifest, nil
}

// EnsureProjectRuntimeAssets ensures essential runtime folders (external scripts, lib DLLs, data, font, sound, video) exist in project
func EnsureProjectRuntimeAssets(engineDir, projectDir string) error {
	if engineDir == "" || projectDir == "" {
		return nil
	}

	foldersToCopy := []string{"external", "lib", "data", "font", "sound", "stages", "video"}
	for _, folder := range foldersToCopy {
		srcFolder := filepath.Join(engineDir, folder)
		if fi, err := os.Stat(srcFolder); err == nil && fi.IsDir() {
			destFolder := filepath.Join(projectDir, folder)
			_ = copyDirRecursive(srcFolder, destFolder)
		}
	}
	return nil
}

func copyDirRecursive(src, dest string) error {
	return filepath.Walk(src, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}

		relPath, err := filepath.Rel(src, path)
		if err != nil {
			return nil
		}

		targetPath := filepath.Join(dest, relPath)

		if info.IsDir() {
			return os.MkdirAll(targetPath, 0755)
		}

		// Don't overwrite if destination file already exists
		if _, err := os.Stat(targetPath); err == nil {
			return nil
		}

		return copyFile(path, targetPath)
	})
}

func copyFile(src, dest string) error {
	if err := os.MkdirAll(filepath.Dir(dest), 0755); err != nil {
		return err
	}

	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()

	out, err := os.Create(dest)
	if err != nil {
		return err
	}
	defer out.Close()

	if _, err := io.Copy(out, in); err != nil {
		return err
	}

	return out.Sync()
}
