// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project} from '../models';
import {engine} from '../models';
import {config} from '../models';

export function CreateProject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<project.ProjectManifest>;

export function DeleteEngine(arg1:string):Promise<void>;

export function DownloadEngine(arg1:string):Promise<void>;

export function FetchAvailableEngines():Promise<Array<engine.ReleaseInfo>>;

export function GetInstalledEngines():Promise<Array<engine.InstalledEngine>>;

export function GetRecentProjects():Promise<Array<string>>;

export function GetSettings():Promise<config.Settings>;

export function IsProjectRunning(arg1:string):Promise<boolean>;

export function LaunchProject(arg1:string):Promise<void>;

export function OpenFolderInExplorer(arg1:string):Promise<void>;

export function OpenProject(arg1:string):Promise<project.ProjectManifest>;

export function SelectDirectoryDialog(arg1:string):Promise<string>;

export function SelectProjectDirectoryDialog():Promise<string>;

export function StopProject(arg1:string):Promise<void>;

export function UpdateSettings(arg1:config.Settings):Promise<void>;
