// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function CreateProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2, arg3, arg4);
}

export function DeleteEngine(arg1) {
  return window['go']['main']['App']['DeleteEngine'](arg1);
}

export function DownloadEngine(arg1) {
  return window['go']['main']['App']['DownloadEngine'](arg1);
}

export function FetchAvailableEngines() {
  return window['go']['main']['App']['FetchAvailableEngines']();
}

export function GetInstalledEngines() {
  return window['go']['main']['App']['GetInstalledEngines']();
}

export function GetRecentProjects() {
  return window['go']['main']['App']['GetRecentProjects']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function IsProjectRunning(arg1) {
  return window['go']['main']['App']['IsProjectRunning'](arg1);
}

export function LaunchProject(arg1) {
  return window['go']['main']['App']['LaunchProject'](arg1);
}

export function OpenFolderInExplorer(arg1) {
  return window['go']['main']['App']['OpenFolderInExplorer'](arg1);
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function OpenProjectLogsFolder(arg1) {
  return window['go']['main']['App']['OpenProjectLogsFolder'](arg1);
}

export function SelectDirectoryDialog(arg1) {
  return window['go']['main']['App']['SelectDirectoryDialog'](arg1);
}

export function SelectProjectDirectoryDialog() {
  return window['go']['main']['App']['SelectProjectDirectoryDialog']();
}

export function StopProject(arg1) {
  return window['go']['main']['App']['StopProject'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function VerifyAndRepairProject(arg1) {
  return window['go']['main']['App']['VerifyAndRepairProject'](arg1);
}
