// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project} from '../models';
import {engine} from '../models';
import {config} from '../models';

export function CancelDownload(arg1:string):Promise<void>;

export function CreateProject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<project.ProjectManifest>;

export function DeleteEngine(arg1:string):Promise<void>;

export function DetectExistingGame(arg1:string):Promise<project.ExistingGameInspection>;

export function DownloadEngine(arg1:string):Promise<void>;

export function FetchAvailableEngines():Promise<Array<engine.ReleaseInfo>>;

export function GetEngineBackups(arg1:string):Promise<Array<project.EngineBackupInfo>>;

export function GetGameConfig(arg1:string):Promise<Record<string, string>>;

export function GetInstalledEngines():Promise<Array<engine.InstalledEngine>>;

export function GetProjectLogs(arg1:string):Promise<string>;

export function GetRecentProjects():Promise<Array<string>>;

export function GetSettings():Promise<config.Settings>;

export function ImportExistingGame(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<project.ProjectManifest>;

export function ImportExistingGameWithOptions(arg1:project.ImportOptions):Promise<project.ProjectManifest>;

export function InspectGameConfig(arg1:string):Promise<config.ConfigInspectionResult>;

export function InspectProjectDifferences(arg1:string):Promise<project.ProjectDiffSummary>;

export function IsProjectRunning(arg1:string):Promise<boolean>;

export function LaunchProject(arg1:string):Promise<void>;

export function LaunchProjectWithOptions(arg1:string,arg2:Array<string>):Promise<void>;

export function OpenFolderInExplorer(arg1:string):Promise<void>;

export function OpenProject(arg1:string):Promise<project.ProjectManifest>;

export function OpenProjectLogsFolder(arg1:string):Promise<void>;

export function RemoveRecentProject(arg1:string):Promise<void>;

export function RepairGameConfig(arg1:string):Promise<void>;

export function ResetGameConfig(arg1:string):Promise<void>;

export function RollbackProjectEngine(arg1:string,arg2:string):Promise<void>;

export function SaveGameConfig(arg1:string,arg2:Record<string, string>):Promise<void>;

export function SelectDirectoryDialog(arg1:string):Promise<string>;

export function SelectProjectDirectoryDialog():Promise<string>;

export function StopProject(arg1:string):Promise<void>;

export function SwitchProjectEngine(arg1:string,arg2:string):Promise<void>;

export function SyncProjectAssets(arg1:project.AssetSyncOptions):Promise<project.VerificationReport>;

export function UpdateSettings(arg1:config.Settings):Promise<void>;

export function VerifyAndRepairProject(arg1:string):Promise<project.VerificationReport>;

export function VerifyAndRepairProjectWithMode(arg1:string,arg2:boolean):Promise<project.VerificationReport>;
