// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddVaultAssetToProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddVaultAssetToProject'](arg1, arg2, arg3);
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function CreateProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2, arg3, arg4);
}

export function CreateVault(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateVault'](arg1, arg2, arg3);
}

export function DeleteEngine(arg1) {
  return window['go']['main']['App']['DeleteEngine'](arg1);
}

export function DeleteVaultAsset(arg1, arg2) {
  return window['go']['main']['App']['DeleteVaultAsset'](arg1, arg2);
}

export function DetectExistingGame(arg1) {
  return window['go']['main']['App']['DetectExistingGame'](arg1);
}

export function DownloadEngine(arg1) {
  return window['go']['main']['App']['DownloadEngine'](arg1);
}

export function ExportProjectAssetsToVault(arg1, arg2) {
  return window['go']['main']['App']['ExportProjectAssetsToVault'](arg1, arg2);
}

export function FetchAvailableEngines() {
  return window['go']['main']['App']['FetchAvailableEngines']();
}

export function GetEngineBackups(arg1) {
  return window['go']['main']['App']['GetEngineBackups'](arg1);
}

export function GetGameConfig(arg1) {
  return window['go']['main']['App']['GetGameConfig'](arg1);
}

export function GetInstalledEngines() {
  return window['go']['main']['App']['GetInstalledEngines']();
}

export function GetProjectFightersAndStages(arg1) {
  return window['go']['main']['App']['GetProjectFightersAndStages'](arg1);
}

export function GetProjectLogs(arg1) {
  return window['go']['main']['App']['GetProjectLogs'](arg1);
}

export function GetProjectRoster(arg1) {
  return window['go']['main']['App']['GetProjectRoster'](arg1);
}

export function GetRecentProjects() {
  return window['go']['main']['App']['GetRecentProjects']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVaultAssets(arg1) {
  return window['go']['main']['App']['GetVaultAssets'](arg1);
}

export function GetVaults() {
  return window['go']['main']['App']['GetVaults']();
}

export function ImportExistingGame(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ImportExistingGame'](arg1, arg2, arg3, arg4, arg5);
}

export function ImportExistingGameWithOptions(arg1) {
  return window['go']['main']['App']['ImportExistingGameWithOptions'](arg1);
}

export function IngestAsset(arg1, arg2, arg3) {
  return window['go']['main']['App']['IngestAsset'](arg1, arg2, arg3);
}

export function IngestAssets(arg1, arg2, arg3) {
  return window['go']['main']['App']['IngestAssets'](arg1, arg2, arg3);
}

export function InspectGameConfig(arg1) {
  return window['go']['main']['App']['InspectGameConfig'](arg1);
}

export function InspectProjectDifferences(arg1) {
  return window['go']['main']['App']['InspectProjectDifferences'](arg1);
}

export function IsProjectRunning(arg1) {
  return window['go']['main']['App']['IsProjectRunning'](arg1);
}

export function LaunchProject(arg1) {
  return window['go']['main']['App']['LaunchProject'](arg1);
}

export function LaunchProjectWithOptions(arg1, arg2) {
  return window['go']['main']['App']['LaunchProjectWithOptions'](arg1, arg2);
}

export function OpenFolderInExplorer(arg1) {
  return window['go']['main']['App']['OpenFolderInExplorer'](arg1);
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function OpenProjectLogsFolder(arg1) {
  return window['go']['main']['App']['OpenProjectLogsFolder'](arg1);
}

export function RegisterVault(arg1) {
  return window['go']['main']['App']['RegisterVault'](arg1);
}

export function RemoveRecentProject(arg1) {
  return window['go']['main']['App']['RemoveRecentProject'](arg1);
}

export function RemoveVaultAssetFromProject(arg1, arg2) {
  return window['go']['main']['App']['RemoveVaultAssetFromProject'](arg1, arg2);
}

export function RepairGameConfig(arg1) {
  return window['go']['main']['App']['RepairGameConfig'](arg1);
}

export function ResetGameConfig(arg1) {
  return window['go']['main']['App']['ResetGameConfig'](arg1);
}

export function RollbackProjectEngine(arg1, arg2) {
  return window['go']['main']['App']['RollbackProjectEngine'](arg1, arg2);
}

export function SaveGameConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveGameConfig'](arg1, arg2);
}

export function SaveProjectRoster(arg1, arg2) {
  return window['go']['main']['App']['SaveProjectRoster'](arg1, arg2);
}

export function SelectArchiveDialog() {
  return window['go']['main']['App']['SelectArchiveDialog']();
}

export function SelectDirectoryDialog(arg1) {
  return window['go']['main']['App']['SelectDirectoryDialog'](arg1);
}

export function SelectMultipleArchivesDialog() {
  return window['go']['main']['App']['SelectMultipleArchivesDialog']();
}

export function SelectProjectDirectoryDialog() {
  return window['go']['main']['App']['SelectProjectDirectoryDialog']();
}

export function StopProject(arg1) {
  return window['go']['main']['App']['StopProject'](arg1);
}

export function SwitchProjectEngine(arg1, arg2) {
  return window['go']['main']['App']['SwitchProjectEngine'](arg1, arg2);
}

export function SyncProjectAssets(arg1) {
  return window['go']['main']['App']['SyncProjectAssets'](arg1);
}

export function UnregisterVault(arg1) {
  return window['go']['main']['App']['UnregisterVault'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateVaultAsset(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateVaultAsset'](arg1, arg2, arg3);
}

export function VerifyAndRepairProject(arg1) {
  return window['go']['main']['App']['VerifyAndRepairProject'](arg1);
}

export function VerifyAndRepairProjectWithMode(arg1, arg2) {
  return window['go']['main']['App']['VerifyAndRepairProjectWithMode'](arg1, arg2);
}
